### ISSUE TITLE
无法正常弹出MelonLoader的bootstrap

### ISSUE THREAD

**Issue by jffifa** [ModBahuang/ModBahuang#15]
**先行检查**
在你提交问题之前请先进行如下自检：
- [x] 已安装了 [.NET Framework 4.8 Runtime](https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer) 以及 [Microsoft Visual C++ 2015-2019 Re-distributable](https://aka.ms/vs/16/release/vc_redist.x64.exe)
- [x] 使用的 `MelonLoader` 是在 [3DM Mod站下载的](https://mod.3dmgame.com/mod/173451)（其他地方下载的 `MelonLoader` 不打算支持）。
- [x] 游戏路径中不存在空格。请确保游戏没有被安装在 `Program Files`。
- [x] 在每次游戏更新后都运行了 `installer.exe`

**问题描述**
游戏为steam版，使用3dm mod站的改版MelonLoader，运行了`installer.exe`。只有开始游戏无法正常弹出MelonLoader的bootstrap（就是那个console），会直接进入游戏。换用原版的MelonLoader之后，`Villain`会因为原版没有`OnApplicationLateStart()`无法正常运行。
将`OnApplicationLateStart`改为`OnApplicationStart`后问题才能解决。

**问题复现**
请详细的写出能够重现该问题的具体步骤：
1. 打开 '...'
2. 点击 '....'

**预期行为**
请用清晰而准确的语言描述出你认为本应发生的事情。

**问题截图**
如果可以，请贴出能够显示出问题的详细截图。

**Latest.log**
请贴出你的 `Latest.log` 文件，位于 `鬼谷八荒\MelonLoader`目录下。

**运行环境**
操作系统：Windows10 Professional
问题 Mod：
鬼谷八荒版本：

**额外说明**

**Comment by lolligun** [comment]
关于 bootstrap，我认为应该是在运行时出了异常，但无法确定位置，可能需要更详细的调试。log 文件被创建了吗？如果没有，那可能是由于这几行代码：
```cpp
	if (!OSVersionCheck() || !Game::Initialize())
		return;
	CommandLine::Read();
```
直觉上像是编码问题，你的系统是中文的吗？
另外，mod 站版本的 MelonLoader 是从 https://github.com/LavaGang/MelonLoader/commit/589db6c0c7e4e16e14d800e8a9b97586561c3f43 的基础上编译来的，并没有修改 bootstrap 的代码。我觉得问题出在 https://github.com/LavaGang/MelonLoader/commit/c5c4273945e0c367696405e97f9e94cd2ee493f8 的可能性比较大。你可以和 https://github.com/LavaGang/MelonLoader/commit/0a7818a108891abfada32ee9afbc92f1eaab80bd 对比测试一下。

而关于 `OnApplicationLateStart`，这应该是个 typo，因为我想不到任何使用它而不是 `OnApplicationStart` 的理由。

**Comment by jffifa** [comment]
> 关于 bootstrap，我认为应该是在运行时出了异常，但无法确定位置，可能需要更详细的调试。log 文件被创建了吗？如果没有，那可能是由于这几行代码：
> 
> ```c++
> 	if (!OSVersionCheck() || !Game::Initialize())
> 		return;
> 	CommandLine::Read();
> ```
> 
> 直觉上像是编码问题，你的系统是中文的吗？
> 另外，mod 站版本的 MelonLoader 是从 [LavaGang/MelonLoader@589db6c](https://github.com/LavaGang/MelonLoader/commit/589db6c0c7e4e16e14d800e8a9b97586561c3f43) 的基础上编译来的，并没有修改 bootstrap 的代码。我觉得问题出在 [LavaGang/MelonLoader@c5c4273](https://github.com/LavaGang/MelonLoader/commit/c5c4273945e0c367696405e97f9e94cd2ee493f8) 的可能性比较大。你可以和 [LavaGang/MelonLoader@0a7818a](https://github.com/LavaGang/MelonLoader/commit/0a7818a108891abfada32ee9afbc92f1eaab80bd) 对比测试一下。
> 
> 而关于 `OnApplicationLateStart`，这应该是个 typo，因为我想不到任何使用它而不是 `OnApplicationStart` 的理由。

1. 我是简体中文系统，cmd默认编码应该是cp936，不论安装路径是默认中文的`鬼谷八荒`还是改成`guigubahuang`都无法bootstrap。官方的MelonLoader在路径修改为`guigubahuang`之后是可以正常bootstrap和使用的
2. 你的Villain代码里确实写的是`OnApplicationLateStart()`，我用ILSpy反编译你的Villain.dll的函数签名也是`OnApplicationLateStart()`

**Comment by lolligun** [comment]
> > 关于 bootstrap，我认为应该是在运行时出了异常，但无法确定位置，可能需要更详细的调试。log 文件被创建了吗？如果没有，那可能是由于这几行代码：
> > ```c++
> > 	if (!OSVersionCheck() || !Game::Initialize())
> > 		return;
> > 	CommandLine::Read();
> > ```
> > 
> > 
> > 直觉上像是编码问题，你的系统是中文的吗？
> > 另外，mod 站版本的 MelonLoader 是从 [LavaGang/MelonLoader@589db6c](https://github.com/LavaGang/MelonLoader/commit/589db6c0c7e4e16e14d800e8a9b97586561c3f43) 的基础上编译来的，并没有修改 bootstrap 的代码。我觉得问题出在 [LavaGang/MelonLoader@c5c4273](https://github.com/LavaGang/MelonLoader/commit/c5c4273945e0c367696405e97f9e94cd2ee493f8) 的可能性比较大。你可以和 [LavaGang/MelonLoader@0a7818a](https://github.com/LavaGang/MelonLoader/commit/0a7818a108891abfada32ee9afbc92f1eaab80bd) 对比测试一下。
> > 而关于 `OnApplicationLateStart`，这应该是个 typo，因为我想不到任何使用它而不是 `OnApplicationStart` 的理由。
> 
> 1. 我是简体中文系统，cmd默认编码应该是cp936，不论安装路径是默认中文的`鬼谷八荒`还是改成`guigubahuang`都无法bootstrap，也没有log文件。官方的MelonLoader（我用的版本是`0.3.0 Pre-Release`）在路径修改为`guigubahuang`之后是可以正常bootstrap和使用的。mod站的那个commit（看提交日期是在`0.3.0`之后了）看代码是引入了一些unicode字符串的问题， 但是不应该全英文路径也无法正常运行。
> 2. 你的Villain代码里确实写的是`OnApplicationLateStart()`，我用ILSpy反编译你的Villain.dll的函数签名也是`OnApplicationLateStart()`

1. 由于我没办法复现（而且这实际上属于 `MelonLoader` 仓库的代码 bug），所以希望你可以帮助测试一下。而至于为什么没有使用已发布的 `Pre-Release` 而是使用尚未发布的 `master` 版本，是因为需要对中文路径的支持。
2. 我的意思 Villain 的代码中的 `OnApplicationLateStart` 是 typo。原因是用 IDE 的自动完成时选错了。

对于 2，可能会发布一个 bugfix 版本来修复对 0.3.0 版本的 MelonLoader 的支持（因为我已经遇到了好几个出现这类问题的人）。
而对于 1，在无法复现的情况下我很难进行修复（而且似乎并不普遍）。因此我并不会去更新 Mod 站的 MelonLoader，而是会建议出现和你一样情况的人去使用 `0.3.0` 版本，虽然会麻烦一些。
不过如果你可以帮忙解决，那么十分欢迎 。

**Comment by lolligun** [comment]
在 ae0e829a303b7a224fb75ed2412fe73e693bd171 将 `OnApplicationLateStart` 改成了 `OnApplicationStart`。因此我删掉了 Villain 和 bug 标签
